### ISSUE TITLE
Command failed: ps l

### ISSUE THREAD

**Issue by oleynikd** [neekey/ps#12]
I'm having this error:
```{[Error: Command failed: ps l
] killed: false, code: 1, signal: null, cmd: 'ps l' }```

```

Error: Error: Command failed: ps l

    at /usr/src/app/run.js:78:27
    at /usr/src/app/node_modules/ps-node/lib/index.js:139:20
    at /usr/src/app/node_modules/ps-node/lib/index.js:76:24
    at ChildProcess.exithandler (child_process.js:209:5)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

```

node v5.10.0

Any idea?
Thanks

**Comment by bahmutov** [comment]
I have same error, but only inside docker container

**Comment by oleynikd** [comment]
`ps.lookup()` will pass error if resulting table is empty, which is strange...
I'm not sure why it is empty but I also using this inside Docker and I ended up with `psargs: '-l'`:
```
ps.lookup(
    {
        command: 'my command',
        psargs: '-l'
    },
    (err, resultList) => {
        // code
    }
)
```

**Comment by neekey** [comment]
@oleynikd @bahmutov what operation system are you using? @oleynikd Do you have the same error if you just run `ps l` in your bash?

**Comment by neekey** [comment]
Closing due to inactivity. If you still have this problem, feel free reopen the issue
