### ISSUE TITLE
next is not a function

### ISSUE THREAD

**Issue by jayfunk** [neekey/ps#14]
When I use the kill command I get the exception below. It appears that if the kill function does not have a callback then it will attempt to call the callback. If I have some time Ill try and put in a PR.

Code:
```
ps.lookup({command: 'test.exe'}, (err, results) => {
  results.forEach(result => {
      if (result.pid) {
        console.log(`Killing process ID: ${result.pid}`);
        ps.kill(result.pid);
      }
  });
});
```

Error Message:
```
Killing container process ID: 31244
C:\Users\tcook\projects\performance-test-runner\node_modules\ps-node\lib\index.js:190
                    next( null, stdout );
                    ^
 
TypeError: next is not a function
    at Timeout._onTimeout (C:\Users\tcook\projects\performance-test-runner\node_modules\ps-node\lib\index.js:190:21)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by neekey** [comment]
@jayfunk thanks for submitting this problem, I will fix this problem this weekend : )
