### ISSUE TITLE
'wmic' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by mceachen** [neekey/ps#59]
```
$ npm install -g ps-node
$ node
> const ps = require("ps-node")
undefined
> ps.lookup({command: "node"}, (err, data) => console.dir({err, data}))
undefined
> { err: '\'wmic\' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n',
  data: undefined }
```
Windows 10 build 15063, node v7.4.0, running in a git-bash shell

**Comment by neekey** [comment]
hi @mceachen sorry for the late reply, the error shows that you don't have `wmic` in your windows, which is not normal, can you just manually type `wmic` in your cmd or git-bash to see if it exists first? and can you also try to get to the ps module directory and run `npm run test` to see the result

**Comment by mceachen** [comment]
```
mrm@xps15:~/src$ git clone git@github.com:neekey/ps.git
Cloning into 'ps'...
remote: Counting objects: 361, done.
remote: Total 361 (delta 0), reused 0 (delta 0), pack-reused 361R
Receiving objects: 100% (361/361), 58.94 KiB | 0 bytes/s, done.
Resolving deltas: 100% (170/170), done.
mrm@xps15:~/src$ cd ps
mrm@xps15:~/src/ps (master)$ yarn
yarn install v0.24.6
info No lockfile found.
[1/4] Resolving packages...
warning mocha > jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning mocha > to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
warning mocha > glob > minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 1.55s.
mrm@xps15:~/src/ps (master)$ yarn run test
yarn run v0.24.6
$ node ./node_modules/mocha/bin/mocha -t 0 -R spec test/test.js


  test
    1) "before all" hook


  0 passing (15ms)
  1 failing

  1) test "before all" hook:
     Uncaught TypeError: Cannot read property 'length' of undefined
      at C:\Users\mrm\src\ps\test\test.js:36:28
      at C:\Users\mrm\src\ps\lib\index.js:157:14
      at ChildProcess.<anonymous> (C:\Users\mrm\src\ps\lib\index.js:64:7)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
mrm@xps15:~/src/ps (master)$ npm test

> ps-node@0.1.6 test C:\Users\mrm\src\ps
> node ./node_modules/mocha/bin/mocha -t 0 -R spec test/test.js



  test
    1) "before all" hook


  0 passing (15ms)
  1 failing

  1) test "before all" hook:
     Uncaught TypeError: Cannot read property 'length' of undefined
      at C:\Users\mrm\src\ps\test\test.js:36:28
      at C:\Users\mrm\src\ps\lib\index.js:157:14
      at ChildProcess.<anonymous> (C:\Users\mrm\src\ps\lib\index.js:64:7)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by mceachen** [comment]
Note that running tests from a `cmd` prompt succeeds (but is *really* slow--three minutes to run 11 tests!):

```
C:\Users\mrm\src\ps>npm run test

> ps-node@0.1.6 test C:\Users\mrm\src\ps
> node ./node_modules/mocha/bin/mocha -t 0 -R spec test/test.js



  test
    #lookup()
[child] child process start!
      √ by id (4671ms)
[child] child process start!
      √ by command & arguments (4444ms)
[child] child process start!
      √ by arguments, the matching should be case insensitive  (9587ms)
[child] child process start!
      √ empty result list should be safe  (4251ms)
[child] child process start!
      √ should work correctly with options `aux` (4150ms)
    #kill()
[child] child process start!
      √ kill (31127ms)
      √ should not throw an exception if the callback is undefined
[child] child process start!
      √ should force kill when opts.signal is SIGKILL (29856ms)
[child] child process start!
      √ should throw error when opts.signal is invalid (26283ms)
    #kill() timeout:
[child] child process start!
      √ it should timeout after 30secs by default if the killing is not successful (33622ms)
[child] child process start!
      √ it should be able to set option to set the timeout (32582ms)


  11 passing (3m)
```

FWIW, `wmic` is hiding in %SYSTEMROOT%/wbem, which isn't in my PATH, but it seems like it should have been, according to https://superuser.com/questions/124239/what-is-the-default-path-environment-variable-setting-on-fresh-install-of-window

```
C:\Users\mrm>where wmic
C:\Windows\System32\wbem\WMIC.exe
```

**Comment by neekey** [comment]
hmm... hard to tell why did it happen this way, though it works for me:

![image](https://user-images.githubusercontent.com/499870/27585802-fa1e7c50-5b80-11e7-968c-c31fb17fdcea.png)

Anyway, for your test running in `git-bash`, it seems like there's error occurred during the lookup, can you change the test.js file a little bit to just log out the error to see what had happend?

add `console.log` before [this line](https://github.com/neekey/ps/blob/master/test/test.js#L36):

```
 PS.lookup({arguments: 'node_process_for_test'}, function (err, list) {
      console.log('ps-node debug:', err)
      var processLen = list.length;
      var killedCount = 0;
```
